### PR TITLE
added user/password to mqtt connection

### PR DESCRIPTION
**Pull request by Cyberdoc**
I've added optional user/password parameters to the code. Also I've changed MQTT_CLIENT_ID, so that now the env parameter will be used instead of hostname

### CODE REVIEW

**Comment by rsaikali** [comment]
Hi @Cyberdoc and thank a lot for your enhancements.

Can we make `MQTT_SERVICE_AUTH` defaults to `None` (without quotes) if no user/password is given. Otherwise it will be a string and it will be used by paho mqtt as authentication: as a string not sure it'll work as a "no authentication" mechanism (I didn't try to be honest but I'm pretty sure `None` and `"None"` will be treated differently).

Maybe the same for `MQTT_SERVICE_USER`, default for `os.getenv` should be `None` to be more Pythonic.

Fine for me for `MQTT_CLIENT_ID` I will set it to `HOSTNAME` on my side as I have multiple ones running in a Kubernetes environment, will use the pod name to distinguish running services.

Thanks again for your interest.
Best regards.

**Comment by Cyberdoc** [comment]
Hi @rsaikali,

changed the code following you absolut correct feedback. 

Maybe also it would be an idea, to use for `MQTT_CLIENT_ID` the hostname as fallback, instead of the  `'dht22-mqtt-service'`, so it would like:

`MQTT_CLIENT_ID = os.getenv('MQTT_CLIENT_ID', os.getenv('HOSTNAME'))`

Kind regards,
Michael

**Comment by rsaikali** [comment]
👍
I was thinking the same, but I was too shy to ask.  :-)

**Comment by Cyberdoc** [comment]
Ok, done. 
So you can decide, if you want to merge it into your repo.

**Comment by rsaikali** [comment]
Looks good to me, let's merge.

It should rebuild and publish on [Docker Hub](https://hub.docker.com/repository/docker/rsaikali/dht22-mqtt) automatically if you use docker.
I will redeploy on my side to test it.

Thanks again Michael.

**Pull request merged**
